default_platform(:ios)

platform :ios do
  desc "Synchronize certificates and provisioning profiles, build, and upload to TestFlight"
  lane :build_and_upload do
    # Synchroniser les certificats et les profils via match
    match(
      type: "appstore",
      api_key_path: "AuthKey.json",  # Assurez-vous que le fichier AuthKey.json est valide
      git_url: "https://github.com/nadjem/matchFast.git"
    )

    # Incrémenter le numéro de build
    increment_build_number(xcodeproj: "StepRunningCoach.xcodeproj")

    # Construire l'archive de l'application
    gym(
      export_method: "app-store",     # Utiliser la méthode "app-store" pour TestFlight
      scheme: "StepRunningCoach"
    )

    # Télécharger l'IPA sur TestFlight
    pilot(api_key_path: "AuthKey.json")
  end
end
