default_platform(:ios)

platform :ios do
  desc "Build and upload the app to TestFlight"
  lane :build_and_upload do
    increment_build_number(xcodeproj: "StepRunningCoach.xcodeproj")
    # 1. Synchroniser les certificats et les profils avec match
    match(type: "appstore", git_url: "https://github.com/nadjem/matchFast.git")

    # 2. Construire l'archive de l'application (gym fait tout le travail avec Fastlane)
    gym(
      export_method: "app-store",   # Méthode d'exportation pour TestFlight
      scheme: "StepRunningCoach",            # Remplacez par le nom de votre scheme
      project: "StepRunningCoach.xcodeproj"
    )

    # 3. Télécharger l'IPA sur TestFlight
    pilot(
      api_key_path: "AuthKey.json"  # Assurez-vous que ce chemin est correct
    )
  end
end
