name: GitHub Action 

on: 
  push:
    branches:    
      - main
  pull_request:
    branches:    
      - main

jobs:
  deploy:
    name: GitHub Pipeline
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app
        
      - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version
   
      - name: Build Cleanup
        run: |
          xcodebuild clean -project StepRunningCoach.xcodeproj -scheme StepRunningCoach | xcpretty
          
     # - name: Build Test
     #   run: |
     #     xcodebuild test -project StepRunningCoach.xcodeproj -scheme StepRunningCoach -destination 'platform=iOS   Simulator,name=iPhone 14,OS=16.2' | xcpretty -s
      
      - name: Build Archive
        uses: yukiarrr/ios-build-action@v1.5.0  
        with:
          project-path: StepRunningCoach.xcodeproj
          scheme: StepRunningCoach
          configuration: Release
          export-options: ./Support/ExportOptions.plist
          p12-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          mobileprovision-base64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}

      - name:  Log    
        if: always()
        run: tail -n 10 /Users/runner/Library/Logs/gym/StepRunningCoach-StepRunningCoach.log
        
      - name: Saving IPA File
        uses: actions/upload-artifact@v2   
        with:
          name: ipa
          path: ./**.ipa
          
      - name: Upload App
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: |
          xcrun altool --upload-app -t ios -f ./**.ipa -u "$APPLEID_USERNAME" -p "$APPLEID_PASSWORD" --verbose
