name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true    

jobs:
  build:
    name: Build and test
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode  
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer  
    - name: Deploy
      uses: vfrascello/xcode-deploy@v1.5
      with:
            xcode-version: '14.0'
            configuration: 'Release'
            scheme: 'StepRunningCoach'
           # path-to-export-options: 'ExportOptions.plist'
            update-build: true
            install-pods: false
            resolve-package-dependencies: true
            distribution-certificate-p12: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
            distribution-certificate-password: ${{ secrets.P12_PASSWORD }}
            app-store-provisioning-profile: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64}}
            auth-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
            auth-key-issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
            auth-key-p8: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

