name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true    

jobs:
  build:
    name: Build and test
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode  
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer  
    - uses: yukiarrr/ios-build-action@v1.11.0
      with:
          project-path: StepRunningCoach.xcodeproj
          p12-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          mobileprovision-base64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          code-signing-identity: "iOS Distribution"
          team-id: "ZBG76PH7D9"
          workspace-path: StepRunningCoach.xcodeproj # optional
    
