name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true    

jobs:
  build:
    name: Build and test
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode  
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer  
    - uses: sparkfabrik/ios-build-action@v2.3.0
      with:
          upload-to-testflight: false
          increment-build-number: true
          build-pods: false
          pods-path: "ios/Podfile"
          configuration: Release
          export-method: app-store
          project-path: StepRunningCoach.xcodeproj
          scheme: StepRunningCoach
          output-path: build-${{ github.sha }}.ipa
          apple-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          apple-key-issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          apple-key-content: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          team-id: ${{ secrets.TEAM_ID }}
          team-name: ${{ secrets.TEAM_NAME }}
          #match-password: ${{ secrets.MATCH_PASSWORD }}
          #match-git-url: ${{ secrets.MATCH_GIT_URL }}
          #match-git-basic-authorization: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          #match-build-type: "appstore"
          browserstack-upload: false
          #browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
          #browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          #fastlane-env: stage
          ios-app-id: com.nadjem.StepRunningCoach

