name: iOS Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:     

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install fastlane
        run: |
          gem install fastlane    

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Delete corrupted Package.resolved
        run: |
          if [ -f StepRunningCoach.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved ]; then
            rm StepRunningCoach.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
          fi
          
      - name: Update OpenSSL
        run: |
          brew update && brew upgrade openssl
          
       # Créer le fichier JSON proprement
      - name: Create AuthKey.json
        run: |
          echo '{
            "key_id": "${{ secrets.APPSTORE_API_KEY_ID }}",
            "issuer_id": "${{ secrets.APPSTORE_ISSUER_ID }}",
            "key": "${{ secrets.APPSTORE_API_PRIVATE_KEY }}",
            "is_key_content_base64": true,
            "in_house": false
          }' > AuthKey.json

      - name: Setup Fastlane and Authenticate with Apple
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}  # Ajout du mot de passe ici
        run: |
          fastlane match appstore --api_key_path AuthKey.json

      - name: List Provisioning Profiles
        run: |
          security find-identity -v -p codesigning
          ls ~/Library/MobileDevice/Provisioning\ Profiles

          
      - name: Build and Archive
        run: |
          xcodebuild -project StepRunningCoach.xcodeproj \
            -scheme StepRunningCoach \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/StepRunningCoach.xcarchive \
            clean archive \
            -allowProvisioningUpdates \ 
            CODE_SIGN_STYLE="Automatic" \

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/StepRunningCoach.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build

      - name: Upload to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > AuthKey.p8
          xcrun altool --upload-app -f $PWD/build/StepRunningCoach.ipa \
            --type ios \
            --apiKey $APP_STORE_CONNECT_API_KEY_ID \
            --apiIssuer $APP_STORE_CONNECT_API_ISSUER_ID \
            --apiKey AuthKey.p8
