name: iOS Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Fastlane
        run: |
          gem install fastlane    

      - name: Create AuthKey.json
        run: |
          echo '{
            "key_id": "${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}",
            "issuer_id": "${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}",
            "key": "${{ secrets.APP_STORE_CONNECT_API_KEY }}"
          }' > AuthKey.json

      - name: Run Fastlane to build and upload to TestFlight
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}  # Mot de passe pour match si nécessaire
        run: |
          fastlane build_and_upload
