name: iOS Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Delete corrupted Package.resolved
        run: |
          if [ -f StepRunningCoach.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved ]; then
            rm StepRunningCoach.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
          fi

      - name: Resolve Swift Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project StepRunningCoach.xcodeproj

      - name: Build and Archive
        run: |
          xcodebuild -project StepRunningCoach.xcodeproj \
            -scheme StepRunningCoach \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/StepRunningCoach.xcarchive \
            clean archive \
            -allowProvisioningUpdates

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/StepRunningCoach.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build

      - name: Upload to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > AuthKey.p8
          xcrun altool --upload-app -f $PWD/build/StepRunningCoach.ipa \
            --type ios \
            --apiKey $APP_STORE_CONNECT_API_KEY_ID \
            --apiIssuer $APP_STORE_CONNECT_API_ISSUER_ID \
            --apiKey AuthKey.p8
