name: iOS Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:     

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install fastlane
        run: |
          gem install fastlane

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Delete corrupted Package.resolved
        run: |
          if [ -f StepRunningCoach.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved ]; then
            rm StepRunningCoach.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
          fi

      - name: Update OpenSSL
        run: |
          brew update && brew upgrade openssl

      # Créer le fichier JSON pour l'authentification avec App Store Connect
      - name: Create AuthKey.json
        run: |
          echo '{
            "key_id": "${{ secrets.APPSTORE_API_KEY_ID }}",
            "issuer_id": "${{ secrets.APPSTORE_ISSUER_ID }}",
            "key": "${{ secrets.APPSTORE_API_PRIVATE_KEY }}",
            "is_key_content_base64": true,
            "in_house": false
          }' > AuthKey.json

      # Configurer fastlane et authentifier l'accès Apple avec signature automatique activée
      - name: Setup Fastlane and Authenticate with Apple
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          fastlane match appstore --api_key_path AuthKey.json

      # Activer la signature automatique via fastlane
      - name: Enable automatic code signing
        run: |
          fastlane sigh resign --signing_identity "iPhone Distribution" --provisioning_profile "match AppStore com.nadjem.StepRunningCoach"

      # Utiliser fastlane gym pour construire et exporter l'IPA
      - name: Build and Export IPA using Fastlane
        run: |
          fastlane gym --scheme "StepRunningCoach" \
            --archive_path "$PWD/build/StepRunningCoach.xcarchive" \
            --export_method "app-store" \
            --export_options "ExportOptions.plist" \
            --output_directory "$PWD/build" \
            --output_name "StepRunningCoach.ipa" \
            --clean

      # Utiliser fastlane pilot pour uploader l'IPA sur TestFlight
      - name: Upload IPA to TestFlight using Fastlane
        run: |
          fastlane pilot upload \
            --ipa "$PWD/build/StepRunningCoach.ipa" \
            --api_key_path "AuthKey.json"
